version: '3.8'

services:
  dashboard_app:
    image: stomalovers-dashboard:latest
    build:
      context: .
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    networks:
      - network_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=network_swarm_public"
      - "traefik.http.routers.dashboard.rule=Host(`dash.stomalovers.com.br`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=dashboard"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.dashboard.loadbalancer.server.port=80"

networks:
  network_public:
    external: true
    name: network_swarm_public
