---
version: "3.7"
services:
  wordpressz5szff4:
    image: wordpress:latest
    hostname: wordpressz5szff4
    volumes:
    - wordpressz5szff4_data:/var/www/html
    networks:
    - network_public
    environment:
    - WORDPRESS_DB_NAME=wordpressz5szff4
    - WORDPRESS_DB_HOST=mysql
    - WORDPRESS_DB_PORT=3306
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_PASSWORD=pCbAYnDBY6Ae6RcD
    - WP_REDIS_HOST=redis
    - WP_REDIS_DATABASE=3
    - VIRTUAL_HOST=stomalovers.com.br
    - ADMIN_USER=pqedRBp6ZX279gwB
    - ADMIN_PASS=GLdzf4tOu9L6k6jL
    - ADMIN_EMAIL=flavio.fagundes@gmail.com
    - WP_LOCALE=pt_BR
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - traefik.enable=1
      - traefik.http.routers.wordpressz5szff4.rule=Host(`stomalovers.com.br`)
      - traefik.http.routers.wordpressz5szff4.entrypoints=websecure
      - traefik.http.routers.wordpressz5szff4.priority=1
      - traefik.http.routers.wordpressz5szff4.tls.certresolver=letsencryptresolver
      - traefik.http.routers.wordpressz5szff4.service=wordpressz5szff4
      - traefik.http.services.wordpressz5szff4.loadbalancer.server.port=80
      - traefik.http.services.wordpressz5szff4.loadbalancer.passHostHeader=1
volumes:
  wordpressz5szff4_data:
    external: true
    name: wordpressz5szff4_datad
networks:
  network_public:
    name: network_swarm_public
    external: true
...
